name: 'WindowsAccounts'
doc: 'Windows 平台上用户以及用户组的相关信息收集。'
author: 'NOPTeam'
version: '0.0.1'
sources:
  - type: 'COMMAND'
    supported_os: 'Windows'
    attributes:
      cmd: 'net'
      args:
        - 'user'
  - type: 'COMMAND'
    supported_os: 'Windows'
    attributes:
      cmd: 'net'
      args:
        - 'localgroup'
  - type: 'COMMAND'
    supported_os: 'Windows'
    attributes:
      cmd: 'net'
      args:
        - 'localgroup'
        - 'Users'
  - type: 'COMMAND'
    supported_os: 'Windows'
    attributes:
      cmd: 'net'
      args:
        - 'localgroup'
        - 'Administrators'
  - type: 'WMI'
    supported_os: 'Windows'
    attributes:
      base_object: ''
      query: 'SELECT * FROM Win32_UserAccount'
  - type: 'WMI'
    supported_os: 'Windows'
    attributes:
      base_object: ''
      query: 'SELECT * FROM Win32_Group'
