name: 'WindowsAutoRun'
author: 'NOPTeam'
sources:
  - type: 'PATH'
    supported_os: 'Windows'
    attributes:
      paths:
        - '%%users_appdata%%\Microsoft\Windows\Start'
        - '%%environ_programdata%%\Microsoft\Windows\Start Menu\Programs\Startup'
  - type: 'PATH'
    supported_os: 'Windows'
    attributes:
      paths:
        - '%%environ_systemdrive%%\Users\Default\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_USERS\%%users_sid%%\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
        - 'HKEY_USERS\%%users_sid%%\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnceEx'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\RunOnce'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\RunOnceEx'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_USERS\%%users_sid%%\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows NT\CurrentVersion\Windows\Load'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows NT\CurrentVersion\Windows\Run'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\Load'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\Run'
  - type: 'REGISTRY_VALUE'
    supported_os: 'Windows'
    attributes:
      key_value_pairs:
        - key: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
          value: 'Userinit'
        - key: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
          value: 'Shell'
        - key: 'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Winlogon'
          value: 'Userinit'
        - key: 'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Winlogon'
          value: 'Shell'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce'
        - 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunServices'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\RunServices'
  - type: 'REGISTRY_VALUE'
    supported_os: 'Windows'
    attributes:
      key_value_pairs:
        - key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa'
          value: 'Authentication Packages'
        - key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa'
          value: 'Security Packages'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\OSConfig'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Monitors'
        - 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Environments\*\Drivers\*\*\'
  - type: 'REGISTRY_VALUE'
    supported_os: 'Windows'
    attributes:
      key_value_pairs:
        - key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Monitors\*'
          value: 'Driver'
  - type: 'REGISTRY_VALUE'
    supported_os: 'Windows'
    attributes:
      key_value_pairs:
        - key: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Active Setup\Installed Components\*'
          value: 'StubPath'
  - type: 'REGISTRY_VALUE'
    supported_os: 'Windows'
    attributes:
      key_value_pairs:
        - key: 'HKEY_CURRENT_USER\Environment'
          value: 'UserInitMprLogonScript'
  - type: 'REGISTRY_VALUE'
    supported_os: 'Windows'
    attributes:
      key_value_pairs:
        - key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\'
          value: 'BootExecute'
        - key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager'
          value: 'PendingFileRenameOperations'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Startup'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run'
version: '0.0.1'
doc: 'Windows 平台上自启动相关信息收集。'

---

name: 'WindowsPolicyScripts'
author: 'NOPTeam'
sources:
  - type: 'PATH'
    supported_os: 'Windows'
    attributes:
      paths:
        - 'C:\Windows\System32\GroupPolicy\Machine\Scripts\Startup'
        - 'C:\Windows\System32\GroupPolicy\Machine\Scripts\Shutdown'
        - 'C:\Windows\System32\GroupPolicy\User\Scripts\Logon'
        - 'C:\Windows\System32\GroupPolicy\User\Scripts\Logoff\'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\Scripts'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\*\'
        - 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\*\*\'
  - type: 'REGISTRY_KEY'
    supported_os: 'Windows'
    attributes:
      keys:
        - 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Group Policy\Scripts'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Logoff'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Logoff\*\'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Logoff\*\*\'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Logon'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Logon\*\'
        - 'HKEY_USERS\%%users_sid%%\Software\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Logon\*\*\'
version: '0.0.1'
doc: 'Windows 平台上组策略相关脚本。'
