name: 'WindowsLogs'
author: 'NOPTeam'
sources:
  - type: 'PATH'
    supported_os: 'Windows'
    attributes:
      paths:
        - 'C:\Windows\System32\winevt\Logs\'
version: '0.0.1'
doc: 'Windows 平台上日志信息。'
