name: 'WindowsPasswordFilter'
author: 'NOPTeam'
sources:
  - type: 'REGISTRY_VALUE'
    supported_os: 'Windows'
    attributes:
      key_value_pairs:
        - key: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa'
          value: 'Notification Packages'
version: '0.0.1'
doc: "Password Filter（密码筛选器） 是 Windows 系统支持的一种可插拔认证扩展机制。\n它允许管理员自定义 DLL，在用户修改/设置密码时对新密码进行审核和处理。"
